#!/bin/sh
echo "[uname]" > /etc/asterisk/gui_sysinfo.conf
UNAME="`uname -srmp`"
echo "output =  $UNAME" >> /etc/asterisk/gui_sysinfo.conf

echo "[uptime]" >> /etc/asterisk/gui_sysinfo.conf
UPTIME="`uptime`"
echo "output = $UPTIME" >> /etc/asterisk/gui_sysinfo.conf

echo "[asterisk]" >> /etc/asterisk/gui_sysinfo.conf
ASTERISK="`asterisk -V`"
echo "output = $ASTERISK" >> /etc/asterisk/gui_sysinfo.conf

echo "[today]" >> /etc/asterisk/gui_sysinfo.conf
TODAY="`date`"
echo "output = $TODAY" >> /etc/asterisk/gui_sysinfo.conf

echo "[hostname]" >> /etc/asterisk/gui_sysinfo.conf
HOSTNAME="`hostname -f`"
echo "output = $HOSTNAME" >> /etc/asterisk/gui_sysinfo.conf

echo "[ifconfig]" >> /etc/asterisk/gui_sysinfo.conf
IFCONFIG=`ifconfig | sed -e "s/^/output = /g"`
echo "$IFCONFIG" >> /etc/asterisk/gui_sysinfo.conf

echo "[du]" >> /etc/asterisk/gui_sysinfo.conf
DISKUSAGE=`df -h | sed -e "s/^/output = /g"`
echo "$DISKUSAGE" >> /etc/asterisk/gui_sysinfo.conf

echo "[free]" >> /etc/asterisk/gui_sysinfo.conf
MEMORYUSAGE=`free | sed -e "s/^/output = /g"`
echo "$MEMORYUSAGE" >> /etc/asterisk/gui_sysinfo.conf
