#!/bin/sh
SYSINFO_OUTPUT="/var/lib/asterisk/static-http/config/sysinfo_output.html"



UNAME="`uname -a`"
/bin/echo "<div id=si_uname>$UNAME</div>" > $SYSINFO_OUTPUT

UPTIME="`uptime`"
/bin/echo "<div id=si_uptime>$UPTIME</div>" >> $SYSINFO_OUTPUT

ASTERISK="`/sbin/asterisk -V`"
/bin/echo "<div id=si_astver>$ASTERISK</div>" >> $SYSINFO_OUTPUT

TODAY="`date`"
/bin/echo "<div id=si_date>$TODAY</div>" >> $SYSINFO_OUTPUT

HOSTNAME="`hostname -f`"
/bin/echo "<div id=si_hostname>$HOSTNAME</div>" >> $SYSINFO_OUTPUT

IFCONFIG=`ifconfig`
/bin/echo "<div id=si_ifconfig>$IFCONFIG</div>" >> $SYSINFO_OUTPUT

DISKUSAGE=`df -k`
/bin/echo "<div id=si_du>$DISKUSAGE</div>" >> $SYSINFO_OUTPUT

MEMORYUSAGE=`free`
/bin/echo "<div id=si_free>$MEMORYUSAGE</div>" >> $SYSINFO_OUTPUT

cfstatus=`mount | grep "\/dev\/hda1"`
if [ -n "$cfstatus" ]
then
/bin/echo "<div id=cf_status>1</div>" >> $SYSINFO_OUTPUT
else
/bin/echo "<div id=cf_status>0</div>" >> $SYSINFO_OUTPUT
fi

/bin/echo "<div id=temp1_status>" >> $SYSINFO_OUTPUT
/bin/cat /sys/bus/i2c/devices/0-0049/temp1_input >> $SYSINFO_OUTPUT
/bin/echo "</div>" >> $SYSINFO_OUTPUT

/bin/echo "<div id=temp2_status>" >> $SYSINFO_OUTPUT
/bin/cat /sys/bus/i2c/devices/0-004a/temp1_input >> $SYSINFO_OUTPUT
/bin/echo "</div>" >> $SYSINFO_OUTPUT

/bin/echo "<div id=bkp_files>" >> $SYSINFO_OUTPUT
ls /var/lib/asterisk/sounds/backups/ >> $SYSINFO_OUTPUT
/bin/echo "</div>" >> $SYSINFO_OUTPUT

/bin/echo "<div id=rec_files>" >> $SYSINFO_OUTPUT
/bin/mkdir -p /var/lib/asterisk/sounds/record
ls /var/lib/asterisk/sounds/record/ >> $SYSINFO_OUTPUT
/bin/echo "</div>" >> $SYSINFO_OUTPUT

/bin/echo "<div id=sound_files>" >> $SYSINFO_OUTPUT
/bin/mkdir -p /var/lib/asterisk/sounds
ls /var/lib/asterisk/sounds/ >> $SYSINFO_OUTPUT
/bin/echo "</div>" >> $SYSINFO_OUTPUT

