#!/bin/sh
# Start up file for network.  Can anyone modify this
# so that if dhcpd fails, it sets a static IP?

case $1 in
	start) rm -f /var/run/dhcpcd*;
               dhcpcd & sleep 5;;
	stop) killall -9 dhcpcd;
	      rm -f /var/run/dhcpcd*;;
	enable) rm -f /etc/rc.d/S10network; 
	        ln -s /etc/init.d/network /etc/rc.d/S10network;;
	disable) rm -f /etc/rc.d/S10network;;
        *) cat <<EOF;;
Syntax: /etc/init.d/network [command]

Available commands:
        start   Start the service
        stop    Stop the service
        enable  Enable service autostart
        disable Disable service autostart
EOF
esac

        
