#!/bin/sh
# David Rowe 11 May 2008
#
# Plugin to monitor the number of IAX2 registrations.
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Asterisk iax registrations'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Registrations'
	echo 'graph_category asterisk'
	echo 'registrations.draw AREA'
	echo 'registrations.label registrations'
	exit 0
fi

echo -n "registrations.value "
asterisk -rx 'iax2 show registry' 2>/dev/null | grep Registered | wc | awk '{ print $1 }' 
