#!/bin/sh
# David Rowe 24 May 2008
#
# Plugin to monitor wispcar restart flag.  This could be:
#  0 - OK
#  1 - wispcar rebooted
#  2 - restart due to watchdog firing
#  3 - restart due to sleep
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Wispcar restart'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Restart'
	echo 'graph_category wispcar'
	echo 'restart.draw AREA'
	echo 'restart.label Restart'
	exit 0
fi

echo -n "restart.value "
if [ -f /tmp/restart ]
then
  cat /tmp/restart
  rm -f /tmp/restart
else
  echo 0
fi
