#!/bin/sh
# David Rowe 24 May 2008
#
# Plugin to monitor wispcar watchdog timer.
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Wispcar watchdog'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Watchdog'
	echo 'graph_category wispcar'
	echo 'watchdog.draw AREA'
	echo 'watchdog.label watchdog'
	exit 0
fi

echo -n "watchdog.value "
cat /tmp/w | awk '{ print $6 }' 
