#!/bin/sh
# Start up file for Dnsmasq

case $1 in
	start) dnsmasq -d >/dev/null 2>/dev/null & ;;
	stop) killall -9 dnsmasq;;
	enable) rm -f /etc/rc.d/S25dnsmasq;
		ln -s /etc/init.d/dnsmasq /etc/rc.d/S25dnsmasq;;
	disable) rm -f /etc/rc.d/S25dnsmasq;;
	*) cat <<EOF;;
Syntax: /etc/init.d/dnsmasq [command]

Available commands:
	start	Start the service
	stop	Stop the service
	enable	Enable service autostart
	disable	Disable service autostart
EOF
esac
