#!/bin/sh
# wispcard shell script
#
# Wispcar daemon
#
# 1/ Polls wispcar every second.
# 2/ Resets watchdog timer every 8 seconds.
#
# Note (1) or (2) causes wispcar script to run, as
# string wispcar sends starts with 'wispcar'

count=0
while [ 1 ]
do
  sleep 1
  count=`expr $count + 1`
  if [ $count -ge 5 ]
  then
    count=0
    echo -n 'w' > /dev/ttyBF0
  else
    echo -n '.' > /dev/ttyBF0
  fi
done
