#!/bin/sh

echo $0 $1 $2 $3 $4 $5 $6 $7 $8 $9 > /tmp/w

# translate restart flag into a number for munin

case $9 in
	b) echo 1 > /tmp/restart;;	
	w) echo 2 > /tmp/restart;;
	s) echo 3 > /tmp/restart;;
esac
